# Dependencies
markdown: redcarpet
highlighter: pygments
gems:
  - jekyll-last-modified-at

# Setup
name: dim Jekyll Theme
title: dim Jekyll Theme
tagline: "A simple plain Jekyll theme"
description: "A simple plain Jekyll theme"

source: src
destination: web

# Local Development
baseurl: "http://localhost:3000"

# Production
# baseurl: "http://greendius.github.io/skeleton" # the subpath of your site, e.g. /blog/
# url: "http://greendius.github.io/skeleton/" # the base hostname & protocol for your site

version: alpha

# permalink: pretty
permalink: /:categories/:title/

# excerpt_separator: <!--more-->

exclude: [todo.html]

# Others
author:
  name: "K Worapon"
  url: "google.com"

github:
  repo: ""
  
encoding: "utf-8"